### ISSUE TITLE
Setting up user gives error

### ISSUE THREAD

**Issue by csillab** [farkasmate/vagrant-junos_cli#2]
If the cmd file contains the following line, the provisioner will fail:

```
set system login user junos-user authentication encrypted-password "$1$bH4C08tX$hkVKHt7hMplI.OGdRe8a8."
```

```bash
 $ vagrant provision
==> vqfx1: Running provisioner: junos_cli...
    vqfx1: Running: /var/folders/v0/c_cv8p_14yl75p1y3sn08blw0000gn/T/vagrant-shell20180314-79439-nnd7pf.cmd
==> vqfx1: bH4C08tX: Undefined variable.
```

Using single quotes have not resolved the issue, but accepted by the device (tested in normal cli).

**Comment by farkasmate** [comment]
I replicated the issue.

From the `vagrant provision --debug` log:

```
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: /usr/sbin/cli -c "configure private;  set system login user junos-user authentication encrypted-password "$1$bH4C08tX$hkVKHt7hMplI.OGdRe8a8.";  show | compare;  commit;exit;" (sudo=false)
DEBUG ssh: stderr: bH4C08tX: Undefined variable.
```

I think the double-quotes should be replaced in the plugin with single-quotes:
```
/usr/sbin/cli -c 'show version'
```
And the provision script should avoid using single quotes.

Does it sound feasible?

**Comment by farkasmate** [comment]
Hi @CsilLAB,

Eventually I found a better solution, both single and double quotes are supported now.
