### ISSUE TITLE
junos_cli does not work with vSRX3.0

### ISSUE THREAD

**Issue by spinoshi** [farkasmate/vagrant-junos_cli#5]
Hello, 
a new version of SRX called vSRX3.0 is available for evaluation as .ova and works perfectly with virtualbox. It is based on JUNOS 18.4. 
After making a custom box, I tried to use junos_cli to push some config and it does not work. 
The problem seems to be in the "prepare" script in provisioner.rb: 
```        
 prepare = "/sbin/sh -c '\
if [ ! -d ~/.vagrant-junos_cli/bin ]; then\
  /bin/mkdir -p ~/.vagrant-junos_cli/bin;\
  /bin/ln -s /bin/echo ~/.vagrant-junos_cli/bin/printf;\
  /bin/ln -s /bin/echo ~/.vagrant-junos_cli/bin/export;\
  /bin/echo setenv PATH \\~/.vagrant-junos_cli/bin:\\$PATH >> ~/.cshrc;\
fi'"

            cli_oneliner = "/usr/sbin/cli -f #{config.upload_path}"
            clean_up = "/bin/rm #{config.upload_path}"
            [prepare, cli_oneliner, clean_up].each do |command|
```
In detail, .cshrc is on a read-only filesystem, so the: ```  /bin/echo setenv PATH \\~/.vagrant-junos_cli/bin:\\$PATH >> ~/.cshrc;\``` fails. 

Removing the prepare part: ```[cli_oneliner, clean_up].each do |command|``` everything seems to work. 
Do you think we can include a case when "prepare" is not executed? Am I missing something?

Thanks! 
Simone

**Comment by farkasmate** [comment]
Hi Simone,

Can you please guide me to a download page for vSRX3.0?
Also, please attach a `Vagrantfile` to test with.

Cheers,
Mate

**Comment by spinoshi** [comment]
HI Mate, 

You can download the image from the juniper website: 
<https://webdownload.juniper.net/swdl/dl/secure/site/1/record/101549.html?pf=vSRX3.0>
(You need a valid Juniper account)
The vagrantfile that I am using with the box (when I do package) is: 
```

# The contents below were provided by the Packer Vagrant post-processor

# The contents below (if any) are custom contents provided by the
# Packer template during image build.
# -*- mode: ruby -*-
# vi: set ft=ruby :

require "vagrant-host-shell"
require "vagrant-junos"

Vagrant.configure('2') do |config|
  config.vm.box = 'geant/junos-vsrx3-18.4R1'
  # Disable the default shared folder between the guest and host
  # Shared folders are not supported, since Junos doesn't support openvmtools
  # If removed, Vagrant will hang at the end of box instantiation
  # DO NOT REMOVE
  config.vm.synced_folder '.', '/vagrant', disabled: true
  # these boxes require now the vagrant-junos guest OS plugin
  # e.g. vagrant plugin install vagrant-junos
  config.vm.guest = :junos
  # changing default from Vagrant to root, since OS detection requires a shell
  # should continue to use Vagrant insecure default public key
  config.ssh.username = 'root'
  # use bourne shell (instead of bash)
  config.ssh.shell = '/bin/sh'
end
```
This instead, is my definition: 
```
  ## Vsrx1   
  config.vm.define "vsrx1" do |vsrx1|
    vsrx1.vm.hostname = "vsrx1"
    #vsrx1.vm.box = "juniper/ffp-12.1X47-D15.4-packetmode"
    vsrx1.vm.box = "geant/junos-vsrx3-18.4R1"
    ## fxp0 connected to NAT network. 
    vsrx1.vm.network "private_network", ip: "10.10.10.10",  auto_config: false ## ge-0/0/0
    vsrx1.vm.network "private_network", virtualbox__intnet: "node1_TO_node2_A" ## ge-0/0/1
    vsrx1.vm.network "private_network", virtualbox__intnet: "node1_TO_node3_A" ## ge-0/0/2
    vsrx1.vm.provision 'junos_cli', path: 'junos-confs/vsrx1.conf'
    vsrx1.vm.provision 'junos_cli', inline: "configure \n set system login user vagrant class super-user authentication ssh-rsa \"#{ssh_pub_key}\"\n commit"

  end
````
where the junos-confs/vsrx1.conf is something like: 
```
cat junos-confs/vsrx1.conf 
configure
set interfaces ge-0/0/0 description "HostOnly network"
set interfaces ge-0/0/0 unit 0 family inet address 192.168.56.11/24
set interfaces ge-0/0/1 description "To node 2"
set interfaces ge-0/0/1 unit 0 family inet address 192.168.12.11/24
set interfaces ge-0/0/2 description "To node 3"
set interfaces ge-0/0/2 unit 0 family inet address 192.168.13.11/24
set interfaces lo0 unit 0 family inet address 10.10.10.11/32
set protocols lldp interface all
set protocols lldp interface ge-0/0/1.0 disable
set chassis aggregated-devices ethernet device-count 10
commit
exit 

```
Thank you very much!
Simone

**Comment by farkasmate** [comment]
Hi Simone,

Thank you for the guidance.
I don't have a Juniper account and I didn't want to provide my phone number for a guest account.

I added two new options to the plugin: https://github.com/farkasmate/vagrant-junos_cli/pull/6
You can skip prepare and cleanup individually.

Can you please test this on the `vsrx3` branch by setting `skip_prepare: true`?
https://github.com/farkasmate/vagrant-junos_cli/blob/vsrx3/example/Vagrantfile#L19

In your config it should look like:
```ruby
...
    vsrx1.vm.provision 'junos_cli', path: 'junos-confs/vsrx1.conf', skip_prepare: true
    vsrx1.vm.provision 'junos_cli', inline: "configure \n set system login user vagrant class super-user authentication ssh-rsa \"#{ssh_pub_key}\"\n commit", skip_prepare: true
...
```

The easiest way to test it if you have Ruby and Bundler installed is to replace `example/Vagrantfile` with your Vagrantfile and run these commands inside the `example` directory:
```bash
bundle install
bundle exec vagrant up --provision
```

**Comment by spinoshi** [comment]
Hi Mate, 

It seems to work perfectly in my environment: 
- setting ```skip_prepare: false``` fails as expected
- setting ```skip_prepare: true``` works ok. 
Will you push this change upstream so the next time I do ```vagrant plugin install junos_cli``` I will get this option? (...stupid question, maybe)

Thanks 
Simone

**Comment by farkasmate** [comment]
Thank you for the testing, Simone.

1.1.0 is merged and pushed to Rubygems.org.
You should be able to do the update now.

Mate

**Comment by spinoshi** [comment]
thanks! 
```
vagrant plugin update
Updating installed plugins...
Fetching: vagrant-junos_cli-1.1.0.gem (100%)
Successfully uninstalled vagrant-junos_cli-1.0.1
Updated 'vagrant-junos_cli' to version '1.1.0'!
```
